config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :item_orders
  resources :items
  resources :orders
  resources :users
  resources :login
  post '/login', to: 'login#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :item_orders
    has_many :orders, through: :item_orders
end

app/models/item_order.rb
class ItemOrder < ApplicationRecord
    belongs_to :order 
    belongs_to :item 
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :item_orders
    has_many :items, through: :item_orders
end

app/models/user.rb
class User < ApplicationRecord
    has_many :orders
    has_secure_password

validates :username, presence: true 
validates :username, uniqueness: true
validates :first_name, uniqueness: true
validates :last_name, uniqueness: true

end
 
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :find_user 
before_action :authorized?  

def find_user
    @user_id = session[:user_id]
    @logged_in = !!@user_id
    
  end


  def logout
    session[:user_id] = nil
  end

  def authorized?
    unless @logged_in
      return redirect_to new_login_path 
    end
  end 


end 

app/controllers/item_orders_controller.rb
class ItemOrdersController < ApplicationController
  def index
    @item_orders =  ItemOrder.all
    @items = Item.all
  end

  def new
    @item_order =  ItemOrder.new
    @items = Item.all
  end

  def show
    @item_order = ItemOrder.find(params[:id])
    @items = Item.all

  end

  def create
  item_order = ItemOrder.find(params[:id])
  item_order.update(user_params)
  redirect_to item_order

  end

  private

  def item_orders_params
    params.require(:item_order).permit()
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

def show
  @item = Item.find(params[:id])
end

def index
  if params[:category] && params[:category] != 'All'
    @items = Item.all.select {|item| item.category == params[:category]}
  else
    @items = Item.all
  end
end



def show
    @item = Item.find(params[:id])
end



end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  skip_before_action :authorized?, only: [:new, :create]  


  def new
    
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      flash[:messages] = "Logging in #{@user.first_name}."
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:messages] = "Incorrect username or password!"
      redirect_to new_login_path
    end
  end

 

def destroy 
  logout 
  redirect_to users_path 
end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

def index
  @orders = Order.all

end

def show
  @order = Order.find(params[:id])
  @item_order = @order.item_order
end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_action :authorized?, only: [:new, :create]


def index 
  @items = Item.all
end

def new 
    @user = User.new 
end

def create 
    @user = User.create(user_params)

    if @user.valid?
       session[:user_id] = @user.id 
       redirect_to @user
    else 
       redirect_to new_user_path    
    end
end 

def show 
    @user = User.find(params[:id]) 
    
end

def edit 
    @user = User.find(params[:id])  
end


def update 
    user = User.find(params[:id]) 
    user.update(user_params) 
    redirect_to user
end


def destroy 
   user = User.find(params[:id])
   user.destroy 
   redirect_to users_path

end

private 

def user_params
params.require(:user).permit(:username, :password, :first_name, :last_name)
end 


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_orders_helper.rb
module ItemOrdersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/item_orders/index.html.erb
<h2>Shopping Cart</h2>

<ul>
<% @item_orders.items.each do |item| %>
<li>
<%= link_to item.product, item %>
</li>
</ul>
<%end %>

app/views/item_orders/new.html.erb
<h2>Shopping Cart</h2>

<%= form_for @item_orders do |add| %>
<%= add.label :item_id %>
<%= add.collection_select :item_id, @items, :id, :product %>
<%= add.submit "Purchase" %>
<% end %>

<%= button_to "Delete #{@item.product}", "/item_orders/#{@item_order.id}", method: :delete %>

app/views/items/index.html.erb
<h1>Welcome to Biashara</h1>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <!-- <span class="navbar-toggler-icon"></span> -->
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
             <li><%= link_to "Login Page", new_login_path %></li>

              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
         <li><%= link_to "Create Account", new_user_path %></li>

          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <div class="col-lg-3">

        <h1 class="my-4">Biashara</h1>
        <div class="list-group">
            <%= link_to 'All', items_path(category: 'All') %>
          <%= link_to 'Shoes', items_path(category: 'Shoes') %>
          <%= link_to 'Accessories',  items_path(category: 'Accessories') %>
          <%= link_to 'Technology', items_path(category: "Technology") %>
        </div>

      </div><!-- -->
      <!-- /.col-lg-3 -->

      <div class="col-lg-9">

        <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            
          
          <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

        <div class="row">

          <% @items.each do |item| %>

            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <%= link_to item.product, item_path(item) %>
                  </h4>
                  <h5>$24.99</h5>
                  <p class="card-text">Category: <%= item.category %></p>
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                  <%=  button_to 'Add to Order', item %>
                </div>
              </div>
            </div>

          <% end %>

          

        </div>
        <!-- /.row -->

      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
    <!-- /.container -->
  </footer>

app/views/items/show.html.erb
<h2> <%= @item.product %>'s Page</h2>

<h3>Product Info</h3>
<p>Category: <%= @item.category %></p>


  <p><%= link_to "Add to Cart", "/item_orders" %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Biashara</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
    <script src="/assets/js/scripts.js" type="71c79c9ccb6c8003e4ba811a-text/javascript"></script>
    <script src="https://ajax.cloudflare.com/cdn-cgi/scripts/a2bd7673/cloudflare-static/rocket-loader.min.js" data-cf-settings="71c79c9ccb6c8003e4ba811a-|49" defer=""></script>
  
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/login/new.html.erb
<h1>Login Profile</h1> 
<%= form_tag('/login') do %>
<%= label_tag :username %>
<%= text_field_tag :username %>
<%= label_tag :password %>
<%= password_field_tag :password %>
<%= submit_tag 'Login' %>
<% end%>

app/views/orders/index.html.erb
<h2>Purchases</h2>

<ul>
<%= @orders.each do |my_order| %>
<li>
Order Number: <%=link_to my_order.order_num, my_order %>
</li>
</ul>

<% end %>

app/views/orders/show.html.erb
<h2>Order Number: <%= @order.order_num %>'s Details</h2>

<h3>Items Purchased</h3>
<!-- show product that was purchased under the order number  -->
<ul>
  @order.item_orders.each do |
  </ul>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>
<%= form_for @user do |f| %>
<%= f.label :username %> 
<%= f.text_field :username %> 
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.submit 'Update'%>
<% end %>

app/views/users/index.html.erb
<h1>Welcome to Biashara</h1>


  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <!-- <span class="navbar-toggler-icon"></span> -->
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
             <li><%= link_to "Login Page", new_login_path %></li>

              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
         <li><%= link_to "Create Account", new_user_path %></li>

          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <div class="col-lg-3">

        <h1 class="my-4">Biashara</h1>
        <div class="list-group">
          <a href="#" class="list-group-item">Category 1</a>
          <a href="#" class="list-group-item">Category 2</a>
          <a href="#" class="list-group-item">Category 3</a>
        </div>

      </div>
      <!-- /.col-lg-3 -->

      <div class="col-lg-9">

        <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            
          
          <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

        <div class="row">

          <% @items.each do |item| %>

            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <%= link_to item.product, item_path(item) %>
                  </h4>
                  <h5>$24.99</h5>
                  <p class="card-text">Category: <%= item.category %></p>
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
            </div>

          <% end %>

          

        </div>
        <!-- /.row -->

      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
    <!-- /.container -->
  </footer>

app/views/users/new.html.erb
<h1>User Sign Up Page</h1> 
<%= form_for @user do |f| %>
<%= f.label :username %>
<%= f.text_field :username %>
<br>
<%= f.label :password %>
<%= f.password_field :password %>
<br> 
<%= f.label :first_name %>
<%= f.text_field :first_name %>
<br> 
<%= f.label :last_name %>
<%= f.text_field :last_name %>
<%= f.submit %> 

<% end %>

app/views/users/show.html.erb
<h1>Show Profile page</h1>  
<h2><%= @user.first_name%>'s Profile</h2>


<%= button_to "Delete Account", user_path(@user), method: "delete" %>